# Generated by Django 2.0.13 on 2019-04-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190410_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ville',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='wilaya',
            field=models.CharField(choices=[('oran', 'oran'), ('alger', 'alger')], max_length=255, null=True),
        ),
    ]
