# Generated by Django 2.0.13 on 2019-04-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190410_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='upc',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
