# Generated by Django 2.0.13 on 2019-04-10 21:29

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_upc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='upc',
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
