# Generated by Django 2.0.13 on 2019-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20190411_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['display_order'], 'verbose_name': 'Service image', 'verbose_name_plural': 'Service images'},
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Display order'),
        ),
    ]
