# Generated by Django 2.0.13 on 2019-04-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20190411_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={},
        ),
    ]
