# Generated by Django 2.0.13 on 2019-04-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20190411_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.FloatField(editable=False, null=True, verbose_name='Rating'),
        ),
    ]
