# Generated by Django 2.0.13 on 2019-04-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20190416_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
    ]
