"""
Django settings for frobshop project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from oscar.defaults import *
from oscar import OSCAR_MAIN_TEMPLATE_DIR
from oscar import get_core_apps
<<<<<<< HEAD
OSCAR_HOMEPAGE = reverse_lazy('acceuil:index')
=======

>>>>>>> d4078a1c350d5d663218bd294360be25f29db914
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'skswx8v&35*!d1ry5q&wwxbe&xiiqlf#r-r(zb66u^)b&s8eii'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

ADMINS = (
    ('Shopaholic', 'Shopaholic.shop118@gmail.com'),
)
OSCAR_SEND_REGISTRATION_EMAIL = True
OSCAR_FROM_EMAIL = 'Shopaholic.shop118@gmail.com'
EMAIL_SUBJECT_PREFIX = '[Shopaholic ] '
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

MANAGERS = ADMINS

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
    'widget_tweaks',
    'apps.service',
    'apps.dashboard.Service',
    'form',
    'apps.about',
<<<<<<< HEAD
    'cashondelivery',
    'paypal',
    'location_field.apps.DefaultConfig',
    'django_filters',
    'bootstrapform',
    'apps.avis',
    'apps.dashboard.Avis',
    'acceuil',



] + get_core_apps(['apps.catalogue', 'apps.dashboard.catalogue', 'apps.checkout', 'apps.shipping'])
=======
    'apps.avis',


] + get_core_apps(['apps.catalogue', 'apps.dashboard.catalogue', 'apps.shipping'])
>>>>>>> d4078a1c350d5d663218bd294360be25f29db914
REVIEW_ALLOW_ANONYMOUS = True
OSCAR_DEFAULT_CURRENCY = 'DA'
OSCAR_SHOP_NAME = 'Shopaholic'
OSCAR_SHOP_TAGLINE = 'Most Loved Place To Buy Online'
USE_LESS = False
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oscar.apps.basket.middleware.BasketMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
<<<<<<< HEAD

=======
>>>>>>> d4078a1c350d5d663218bd294360be25f29db914
]

AUTHENTICATION_BACKENDS = (
    'oscar.apps.customer.auth_backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
)

<<<<<<< HEAD



=======
>>>>>>> d4078a1c350d5d663218bd294360be25f29db914
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
    },
}

ROOT_URLCONF = 'frobshop.urls'

<<<<<<< HEAD
=======

>>>>>>> d4078a1c350d5d663218bd294360be25f29db914
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            OSCAR_MAIN_TEMPLATE_DIR
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.contrib.messages.context_processors.messages',

                'oscar.apps.search.context_processors.search_form',
                'oscar.apps.promotions.context_processors.promotions',
                'oscar.apps.checkout.context_processors.checkout',
                'oscar.apps.customer.notifications.context_processors.notifications',
                'oscar.core.context_processors.metadata',
            ],
        },
    },
]
WSGI_APPLICATION = 'frobshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
        'ATOMIC_REQUESTS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

MEDIA_ROOT = 'media'

MEDIA_URL = '/media/'
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
OSCAR_INITIAL_ORDER_STATUS = 'En attente'
OSCAR_INITIAL_LINE_STATUS = 'En attente'
OSCAR_ORDER_STATUS_PIPELINE = {
    'En attente': ('En cours de livraison', 'annulée',),
    'En cours de livraison': ('livrée', 'annulée',),
    'annulée': (),
}

OSCAR_DASHBOARD_NAVIGATION += [

    {
        'label': ('Tableau de bord'),
        'icon': 'icon-list-ul',
        'url_name': 'Service:service_list',
        'access_fn': lambda user, url_name, url_args, url_kwargs: user.email == "admin.service@gmail.com"
    },
    {
        'label': ('Services'),
        'icon': 'icon-map-marker',
        'children': [
            {
                'label': ('Tous les Services'),
                'url_name': 'Service:service_list',
                'access_fn': lambda user, url_name, url_args, url_kwargs: user.email == "admin.service@gmail.com"
            },
            {
                'label': ('Catégories'),
                'url_name': 'Service:category_list',
                'access_fn': lambda user, url_name, url_args, url_kwargs: user.email == "admin.service@gmail.com" ,
            }
        ]
    },
<<<<<<< HEAD
    {
        'label': ('Avis'),
        'icon': 'icon-edit',
        'url_name': 'Avis:reviews_list',
         'access_fn': lambda user, url_name, url_args, url_kwargs: user.email == "admin.service@gmail.com",

    },

    {
        'label': ('Avis Produits'),
=======

    {
        'label': ('Avis'),
>>>>>>> d4078a1c350d5d663218bd294360be25f29db914
        'icon': 'icon-edit',
         'url_name': 'dashboard:reviews-list',
         'access_fn': lambda user, url_name, url_args, url_kwargs: user.is_staff

    },
<<<<<<< HEAD
{
        'label': ('Services'),
        'icon': 'icon-map-marker',
        'children': [
            {
                'label': ('Tous les Services'),
                'url_name': 'Service:service_list',
                'access_fn': lambda user, url_name, url_args, url_kwargs: user.email == "admin@gmail.com"
            },
            {
                'label': ('Catégories'),
                'url_name': 'Service:category_list',
                'access_fn': lambda user, url_name, url_args, url_kwargs: user.email == "admin@gmail.com" ,
            }
        ]
    },
    {
        'label': ('Avis Services'),
        'icon': 'icon-edit',
        'url_name': 'Avis:reviews_list',
         'access_fn': lambda user, url_name, url_args, url_kwargs: user.email == "admin@gmail.com",

    },


=======
>>>>>>> d4078a1c350d5d663218bd294360be25f29db914
  ]

